// テンプレートマスターデータ
import { EstimateTemplate } from './types';

export const ESTIMATE_TEMPLATES: EstimateTemplate[] = [
  // キッチンリフォーム標準
  {
    id: 'tpl-kitchen-standard',
    name: 'キッチンリフォーム標準',
    description: 'システムキッチン交換を中心とした標準的なキッチンリフォーム',
    category: 'kitchen',
    tags: ['標準', 'システムキッチン', 'I型'],
    isActive: true,
    usageCount: 156,
    lastUsed: new Date('2025-08-20'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-08-20'),
    createdBy: 'admin',
    defaultTaxRate: 10,
    defaultValidDays: 30,
    notes: '※配送費・諸経費は別途お見積りいたします',
    terms: '工事着工後のキャンセルはお受けできません',
    defaultCostRates: {
      material: 0.6,
      labor: 0.7,
      subcontract: 0.8,
    },
    sections: [
      {
        id: 'sec-kitchen-main',
        name: 'キッチン本体',
        order: 1,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-system-kitchen',
            itemName: 'システムキッチン I型2550mm',
            specification: 'LIXIL シエラS 扉:ホワイト/天板:人造大理石',
            unit: 'セット',
            defaultQuantity: 1,
            unitPrice: 450000,
            costPrice: 270000,
            category: 'kitchen',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
            masterItemId: 'shiera-s',
          },
          {
            id: 'itm-kitchen-option1',
            itemName: '食器洗い乾燥機',
            specification: '深型タイプ 約6人分',
            unit: '台',
            defaultQuantity: 1,
            unitPrice: 120000,
            costPrice: 84000,
            category: 'kitchen',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
          {
            id: 'itm-kitchen-option2',
            itemName: 'IHクッキングヒーター',
            specification: '3口IH 75cm幅',
            unit: '台',
            defaultQuantity: 1,
            unitPrice: 180000,
            costPrice: 126000,
            category: 'kitchen',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
        ],
      },
      {
        id: 'sec-kitchen-work',
        name: '施工費',
        order: 2,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-removal',
            itemName: '既存キッチン撤去工事',
            specification: '撤去・処分費含む',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 80000,
            costPrice: 56000,
            category: 'labor',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
          {
            id: 'itm-installation',
            itemName: 'システムキッチン設置工事',
            specification: '組立・設置・調整',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 120000,
            costPrice: 84000,
            category: 'labor',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
          {
            id: 'itm-plumbing',
            itemName: '給排水接続工事',
            specification: '給水・給湯・排水接続',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 60000,
            costPrice: 42000,
            category: 'labor',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
          {
            id: 'itm-electrical',
            itemName: '電気工事',
            specification: '200V配線・コンセント増設',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 45000,
            costPrice: 31500,
            category: 'labor',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: false,
            allowPriceChange: true,
            formula: {
              type: 'linked',
              linkedItemId: 'itm-kitchen-option2',
              calculation: 'linkedItem.quantity > 0 ? 45000 : 0',
            },
          },
        ],
      },
      {
        id: 'sec-kitchen-finish',
        name: '仕上げ工事',
        order: 3,
        isCollapsible: true,
        defaultExpanded: false,
        items: [
          {
            id: 'itm-wall-repair',
            itemName: '壁クロス補修',
            specification: 'キッチン周り部分補修',
            unit: '㎡',
            defaultQuantity: 10,
            unitPrice: 3500,
            costPrice: 2450,
            category: 'finish',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
          {
            id: 'itm-floor-repair',
            itemName: '床補修工事',
            specification: 'クッションフロア張替',
            unit: '㎡',
            defaultQuantity: 8,
            unitPrice: 4500,
            costPrice: 3150,
            category: 'finish',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
        ],
      },
      {
        id: 'sec-kitchen-other',
        name: '諸経費',
        order: 4,
        isCollapsible: false,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-management',
            itemName: '現場管理費',
            specification: '',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 0,
            costPrice: 0,
            category: 'other',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: false,
            formula: {
              type: 'percentage',
              value: 8,
              calculation: 'subtotal * 0.08',
            },
          },
          {
            id: 'itm-general',
            itemName: '一般管理費',
            specification: '',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 0,
            costPrice: 0,
            category: 'other',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: false,
            formula: {
              type: 'percentage',
              value: 10,
              calculation: 'subtotal * 0.10',
            },
          },
        ],
      },
    ],
  },

  // 浴室リフォーム標準
  {
    id: 'tpl-bathroom-standard',
    name: '浴室リフォーム標準',
    description: 'ユニットバス交換を中心とした標準的な浴室リフォーム',
    category: 'bathroom',
    tags: ['標準', 'ユニットバス', '1616サイズ'],
    isActive: true,
    usageCount: 98,
    lastUsed: new Date('2025-08-19'),
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2025-08-19'),
    createdBy: 'admin',
    defaultTaxRate: 10,
    defaultValidDays: 30,
    sections: [
      {
        id: 'sec-bath-main',
        name: 'ユニットバス本体',
        order: 1,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-unit-bath',
            itemName: 'ユニットバス 1616サイズ',
            specification: 'TOTO サザナ Nタイプ',
            unit: 'セット',
            defaultQuantity: 1,
            unitPrice: 850000,
            costPrice: 595000,
            category: 'bathroom',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
          {
            id: 'itm-bath-heater',
            itemName: '浴室暖房乾燥機',
            specification: '天井埋込型 100V',
            unit: '台',
            defaultQuantity: 1,
            unitPrice: 95000,
            costPrice: 66500,
            category: 'bathroom',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
        ],
      },
      {
        id: 'sec-bath-work',
        name: '施工費',
        order: 2,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-bath-removal',
            itemName: '既存浴室解体工事',
            specification: '在来浴室解体・処分',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 120000,
            costPrice: 84000,
            category: 'labor',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
          {
            id: 'itm-bath-install',
            itemName: 'ユニットバス組立設置',
            specification: '組立・防水・設置',
            unit: '式',
            defaultQuantity: 1,
            unitPrice: 180000,
            costPrice: 126000,
            category: 'labor',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: false,
            allowPriceChange: true,
          },
        ],
      },
    ],
  },

  // 外壁塗装
  {
    id: 'tpl-exterior-paint',
    name: '外壁塗装工事標準',
    description: '戸建住宅の外壁・屋根塗装工事',
    category: 'exterior',
    tags: ['外壁', '塗装', 'シリコン'],
    isActive: true,
    usageCount: 67,
    lastUsed: new Date('2025-08-18'),
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2025-08-18'),
    createdBy: 'admin',
    defaultTaxRate: 10,
    defaultValidDays: 30,
    sections: [
      {
        id: 'sec-scaffold',
        name: '仮設工事',
        order: 1,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-scaffold',
            itemName: '足場設置工事',
            specification: '単管足場・メッシュシート込み',
            unit: '㎡',
            defaultQuantity: 200,
            unitPrice: 800,
            costPrice: 560,
            category: 'scaffold',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
        ],
      },
      {
        id: 'sec-wall-paint',
        name: '外壁塗装工事',
        order: 2,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-pressure-wash',
            itemName: '高圧洗浄',
            specification: '外壁・屋根',
            unit: '㎡',
            defaultQuantity: 180,
            unitPrice: 300,
            costPrice: 210,
            category: 'preparation',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
          {
            id: 'itm-wall-primer',
            itemName: '下塗り（シーラー）',
            specification: '外壁全面',
            unit: '㎡',
            defaultQuantity: 150,
            unitPrice: 600,
            costPrice: 420,
            category: 'paint',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
          {
            id: 'itm-wall-paint-main',
            itemName: '中塗り・上塗り',
            specification: 'シリコン系塗料 2回塗り',
            unit: '㎡',
            defaultQuantity: 150,
            unitPrice: 2400,
            costPrice: 1680,
            category: 'paint',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
        ],
      },
      {
        id: 'sec-roof-paint',
        name: '屋根塗装工事',
        order: 3,
        isCollapsible: true,
        defaultExpanded: false,
        items: [
          {
            id: 'itm-roof-primer',
            itemName: '屋根下塗り',
            specification: '錆止め塗料',
            unit: '㎡',
            defaultQuantity: 80,
            unitPrice: 700,
            costPrice: 490,
            category: 'paint',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
          {
            id: 'itm-roof-paint-main',
            itemName: '屋根中塗り・上塗り',
            specification: 'シリコン系塗料 2回塗り',
            unit: '㎡',
            defaultQuantity: 80,
            unitPrice: 2200,
            costPrice: 1540,
            category: 'paint',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
        ],
      },
    ],
  },

  // 電気工事
  {
    id: 'tpl-electrical-led',
    name: 'LED照明交換工事',
    description: 'オフィス・店舗のLED化工事',
    category: 'electrical',
    tags: ['LED', '省エネ', 'オフィス'],
    isActive: true,
    usageCount: 43,
    lastUsed: new Date('2025-08-17'),
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2025-08-17'),
    createdBy: 'admin',
    defaultTaxRate: 10,
    defaultValidDays: 30,
    sections: [
      {
        id: 'sec-led-main',
        name: 'LED照明器具',
        order: 1,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-led-40w',
            itemName: 'LED蛍光灯 40W形',
            specification: '直管型 昼白色 5000K',
            unit: '本',
            defaultQuantity: 50,
            unitPrice: 3500,
            costPrice: 2450,
            category: 'electrical',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
          {
            id: 'itm-led-downlight',
            itemName: 'LEDダウンライト',
            specification: '100W相当 調光対応',
            unit: '台',
            defaultQuantity: 20,
            unitPrice: 8500,
            costPrice: 5950,
            category: 'electrical',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
        ],
      },
      {
        id: 'sec-led-work',
        name: '電気工事',
        order: 2,
        isCollapsible: true,
        defaultExpanded: true,
        items: [
          {
            id: 'itm-led-install',
            itemName: '照明器具交換工事',
            specification: '既存器具撤去・新規取付',
            unit: '台',
            defaultQuantity: 70,
            unitPrice: 2000,
            costPrice: 1400,
            category: 'labor',
            isOptional: false,
            isRequired: true,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
          {
            id: 'itm-switch-update',
            itemName: '調光スイッチ交換',
            specification: 'LED対応型',
            unit: '箇所',
            defaultQuantity: 5,
            unitPrice: 12000,
            costPrice: 8400,
            category: 'electrical',
            isOptional: true,
            isRequired: false,
            allowQuantityChange: true,
            allowPriceChange: true,
          },
        ],
      },
    ],
  },
];

// テンプレート検索用ヘルパー関数
export const searchTemplates = (query: string): EstimateTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return ESTIMATE_TEMPLATES.filter(
    (template) =>
      template.name.toLowerCase().includes(lowerQuery) ||
      template.description?.toLowerCase().includes(lowerQuery) ||
      template.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)),
  );
};

// カテゴリ別取得
export const getTemplatesByCategory = (
  category: string,
): EstimateTemplate[] => {
  return ESTIMATE_TEMPLATES.filter(
    (template) => template.category === category,
  );
};

// 人気順取得
export const getPopularTemplates = (limit: number = 5): EstimateTemplate[] => {
  return [...ESTIMATE_TEMPLATES]
    .sort((a, b) => b.usageCount - a.usageCount)
    .slice(0, limit);
};
