import { EstimateTemplate, TemplateSection, EstimateItem } from '../types';

// ==================== デモテンプレートデータ ====================

/**
 * 10個のデモテンプレート
 * 様々な工事パターンを網羅
 */

// ヘルパー関数：項目作成
function createItem(
  id: string,
  no: number,
  category: string,
  minorCategory: string,
  itemName: string,
  specification: string,
  quantity: number,
  unit: string,
  unitPrice: number,
  costPrice: number = 0,
): EstimateItem {
  return {
    id,
    no,
    category,
    minorCategory,
    itemName,
    specification,
    quantity,
    unit,
    unitPrice,
    amount: quantity * unitPrice,
    remarks: '',
    costPrice,
    costAmount: quantity * costPrice,
    grossProfit: quantity * (unitPrice - costPrice),
    grossProfitRate:
      unitPrice > 0 ? ((unitPrice - costPrice) / unitPrice) * 100 : 0,
  };
}

export const DEMO_TEMPLATES: EstimateTemplate[] = [
  // ==================== 1. 新築住宅（木造2階建て）====================
  {
    id: 'demo-template-001',
    name: '新築住宅（木造2階建て）',
    description: '延床面積100㎡の木造2階建て住宅の標準見積',
    category: '新築',
    scope: 'company',
    sections: [
      {
        id: 'sec-001-1',
        name: '仮設工事',
        majorCategory: '仮設工事',
        items: [
          createItem(
            'item-001-1',
            1,
            '仮設工事',
            '足場・養生',
            '枠組足場',
            'W900×H1700',
            200,
            'm²',
            1500,
            900,
          ),
          createItem(
            'item-001-2',
            2,
            '仮設工事',
            '足場・養生',
            '養生シート',
            'メッシュシート',
            200,
            'm²',
            300,
            180,
          ),
          createItem(
            'item-001-3',
            3,
            '仮設工事',
            '仮設設備',
            '仮設トイレ',
            '水洗式',
            4,
            '月',
            15000,
            9000,
          ),
        ],
      },
      {
        id: 'sec-001-2',
        name: '基礎工事',
        majorCategory: '基礎工事',
        items: [
          createItem(
            'item-001-4',
            4,
            '基礎工事',
            '基礎本体',
            'ベタ基礎',
            'コンクリート打設',
            100,
            'm²',
            8000,
            4800,
          ),
          createItem(
            'item-001-5',
            5,
            '基礎工事',
            '防湿・防水',
            '防湿シート',
            '0.15mm厚',
            100,
            'm²',
            500,
            300,
          ),
        ],
      },
      {
        id: 'sec-001-3',
        name: '木工事',
        majorCategory: '木工事',
        items: [
          createItem(
            'item-001-6',
            6,
            '木工事',
            '構造材',
            '構造用合板',
            '12mm厚',
            80,
            '枚',
            2500,
            1500,
          ),
          createItem(
            'item-001-7',
            7,
            '木工事',
            '断熱材',
            '断熱材',
            'グラスウール',
            150,
            'm²',
            1200,
            720,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 2. リフォーム（水回り全面改修）====================
  {
    id: 'demo-template-002',
    name: 'リフォーム（水回り全面改修）',
    description: 'キッチン・浴室・トイレ・洗面の水回り4点セット',
    category: 'リフォーム',
    scope: 'company',
    sections: [
      {
        id: 'sec-002-1',
        name: 'キッチン工事',
        majorCategory: 'キッチン工事',
        items: [
          createItem(
            'item-002-1',
            1,
            'キッチン工事',
            'システムキッチン',
            'システムキッチン',
            'I型2550mm LIXIL',
            1,
            'セット',
            350000,
            210000,
          ),
          createItem(
            'item-002-2',
            2,
            'キッチン工事',
            'キッチン設備',
            'IHクッキングヒーター',
            '3口IH Panasonic',
            1,
            '台',
            85000,
            51000,
          ),
          createItem(
            'item-002-3',
            3,
            'キッチン工事',
            'キッチン設備',
            'レンジフード',
            'シロッコファン',
            1,
            '台',
            65000,
            39000,
          ),
        ],
      },
      {
        id: 'sec-002-2',
        name: '浴室工事',
        majorCategory: '浴室工事',
        items: [
          createItem(
            'item-002-4',
            4,
            '浴室工事',
            'ユニットバス',
            'ユニットバス',
            '1616サイズ TOTO',
            1,
            'セット',
            450000,
            270000,
          ),
          createItem(
            'item-002-5',
            5,
            '浴室工事',
            '浴室設備',
            '浴室暖房乾燥機',
            '24時間換気機能付',
            1,
            '台',
            95000,
            57000,
          ),
        ],
      },
      {
        id: 'sec-002-3',
        name: '給排水工事',
        majorCategory: '給排水工事',
        items: [
          createItem(
            'item-002-6',
            6,
            '給排水工事',
            '衛生器具',
            'トイレ',
            'タンクレス TOTO',
            1,
            '台',
            180000,
            108000,
          ),
          createItem(
            'item-002-7',
            7,
            '給排水工事',
            '衛生器具',
            '洗面化粧台',
            '幅750mm',
            1,
            '台',
            85000,
            51000,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 3. リノベーション（中古マンション）====================
  {
    id: 'demo-template-003',
    name: 'リノベーション（中古マンション）',
    description: '60㎡マンションのスケルトンリノベーション',
    category: 'リノベーション',
    scope: 'company',
    sections: [
      {
        id: 'sec-003-1',
        name: '解体工事',
        majorCategory: '解体工事',
        items: [
          createItem(
            'item-003-1',
            1,
            '解体工事',
            '内装解体',
            '内装解体',
            'スケルトン解体',
            60,
            'm²',
            2000,
            1200,
          ),
          createItem(
            'item-003-2',
            2,
            '解体工事',
            '廃材処分',
            '廃材処分',
            '2tトラック',
            3,
            '台',
            35000,
            21000,
          ),
        ],
      },
      {
        id: 'sec-003-2',
        name: '内装工事',
        majorCategory: '内装工事',
        items: [
          createItem(
            'item-003-3',
            3,
            '内装工事',
            '床工事',
            'フローリング',
            '複合フローリング',
            60,
            'm²',
            7500,
            4500,
          ),
          createItem(
            'item-003-4',
            4,
            '内装工事',
            '壁・天井工事',
            'クロス',
            'ビニールクロス',
            150,
            'm²',
            1200,
            720,
          ),
        ],
      },
      {
        id: 'sec-003-3',
        name: '電気工事',
        majorCategory: '電気工事',
        items: [
          createItem(
            'item-003-5',
            5,
            '電気工事',
            '配線工事',
            '配線工事',
            '全室配線やり直し',
            1,
            '式',
            150000,
            90000,
          ),
          createItem(
            'item-003-6',
            6,
            '電気工事',
            '照明器具',
            'LED照明',
            'ダウンライト',
            15,
            '箇所',
            8000,
            4800,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 4. 外構工事（駐車場+門扉）====================
  {
    id: 'demo-template-004',
    name: '外構工事（駐車場+門扉）',
    description: 'コンクリート駐車場2台分と門扉・フェンス設置',
    category: '外構',
    scope: 'branch',
    branch: '東京支店',
    sections: [
      {
        id: 'sec-004-1',
        name: '外構工事',
        majorCategory: '諸経費',
        items: [
          createItem(
            'item-004-1',
            1,
            '諸経費',
            'その他経費',
            'コンクリート駐車場',
            '2台分 30㎡',
            30,
            'm²',
            12000,
            7200,
          ),
          createItem(
            'item-004-2',
            2,
            '諸経費',
            'その他経費',
            'カーポート',
            'アルミ製2台用',
            1,
            '基',
            250000,
            150000,
          ),
          createItem(
            'item-004-3',
            3,
            '諸経費',
            'その他経費',
            '門扉',
            'アルミ製両開き',
            1,
            '箇所',
            180000,
            108000,
          ),
          createItem(
            'item-004-4',
            4,
            '諸経費',
            'その他経費',
            'フェンス',
            'アルミ製H1200',
            20,
            'm',
            15000,
            9000,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 5. キッチンリフォーム ====================
  {
    id: 'demo-template-005',
    name: 'キッチンリフォーム',
    description: 'システムキッチン交換と周辺工事',
    category: 'リフォーム',
    scope: 'branch',
    branch: '大阪支店',
    sections: [
      {
        id: 'sec-005-1',
        name: 'キッチン工事',
        majorCategory: 'キッチン工事',
        items: [
          createItem(
            'item-005-1',
            1,
            'キッチン工事',
            'システムキッチン',
            'システムキッチン',
            'L型2550×1650mm クリナップ',
            1,
            'セット',
            450000,
            270000,
          ),
          createItem(
            'item-005-2',
            2,
            'キッチン工事',
            'キッチン設備',
            'IHクッキングヒーター',
            '3口IH',
            1,
            '台',
            85000,
            51000,
          ),
          createItem(
            'item-005-3',
            3,
            'キッチン工事',
            'キッチン設備',
            '食器洗い乾燥機',
            'ビルトイン',
            1,
            '台',
            120000,
            72000,
          ),
        ],
      },
      {
        id: 'sec-005-2',
        name: '内装工事',
        majorCategory: '内装工事',
        items: [
          createItem(
            'item-005-4',
            4,
            '内装工事',
            '床工事',
            'キッチンパネル',
            '不燃パネル',
            5,
            'm²',
            8000,
            4800,
          ),
          createItem(
            'item-005-5',
            5,
            '内装工事',
            '床工事',
            'クッションフロア',
            'キッチン用',
            8,
            'm²',
            3500,
            2100,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 6. 浴室リフォーム ====================
  {
    id: 'demo-template-006',
    name: '浴室リフォーム',
    description: 'ユニットバス交換と周辺工事',
    category: 'リフォーム',
    scope: 'branch',
    branch: '名古屋支店',
    sections: [
      {
        id: 'sec-006-1',
        name: '解体工事',
        majorCategory: '解体工事',
        items: [
          createItem(
            'item-006-1',
            1,
            '解体工事',
            '内装解体',
            '既存浴室解体',
            'ユニットバス解体撤去',
            1,
            '式',
            80000,
            48000,
          ),
        ],
      },
      {
        id: 'sec-006-2',
        name: '浴室工事',
        majorCategory: '浴室工事',
        items: [
          createItem(
            'item-006-2',
            2,
            '浴室工事',
            'ユニットバス',
            'ユニットバス',
            '1620サイズ LIXIL',
            1,
            'セット',
            480000,
            288000,
          ),
          createItem(
            'item-006-3',
            3,
            '浴室工事',
            '浴室設備',
            '浴室暖房乾燥機',
            '24時間換気機能付',
            1,
            '台',
            95000,
            57000,
          ),
        ],
      },
      {
        id: 'sec-006-3',
        name: '給排水工事',
        majorCategory: '給排水工事',
        items: [
          createItem(
            'item-006-4',
            4,
            '給排水工事',
            '給水設備',
            '給排水配管工事',
            '配管やり直し',
            1,
            '式',
            60000,
            36000,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 7. トイレリフォーム ====================
  {
    id: 'demo-template-007',
    name: 'トイレリフォーム',
    description: 'トイレ交換と内装リフォーム',
    category: 'リフォーム',
    scope: 'company',
    sections: [
      {
        id: 'sec-007-1',
        name: '給排水工事',
        majorCategory: '給排水工事',
        items: [
          createItem(
            'item-007-1',
            1,
            '給排水工事',
            '衛生器具',
            'トイレ',
            'タンクレス TOTO',
            1,
            '台',
            180000,
            108000,
          ),
          createItem(
            'item-007-2',
            2,
            '給排水工事',
            '給水設備',
            '給排水配管工事',
            '配管接続',
            1,
            '式',
            30000,
            18000,
          ),
        ],
      },
      {
        id: 'sec-007-2',
        name: '内装工事',
        majorCategory: '内装工事',
        items: [
          createItem(
            'item-007-3',
            3,
            '内装工事',
            '壁・天井工事',
            'クロス',
            '防汚クロス',
            12,
            'm²',
            1500,
            900,
          ),
          createItem(
            'item-007-4',
            4,
            '内装工事',
            '床工事',
            'クッションフロア',
            '防水仕様',
            2,
            'm²',
            4000,
            2400,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 8. 屋根外壁塗装 ====================
  {
    id: 'demo-template-008',
    name: '屋根外壁塗装',
    description: '住宅の屋根・外壁塗装工事',
    category: 'リフォーム',
    scope: 'company',
    sections: [
      {
        id: 'sec-008-1',
        name: '仮設工事',
        majorCategory: '仮設工事',
        items: [
          createItem(
            'item-008-1',
            1,
            '仮設工事',
            '足場・養生',
            '枠組足場',
            'W900×H1700',
            200,
            'm²',
            1500,
            900,
          ),
        ],
      },
      {
        id: 'sec-008-2',
        name: '外壁工事',
        majorCategory: '外壁工事',
        items: [
          createItem(
            'item-008-2',
            2,
            '外壁工事',
            '外壁材',
            '外壁塗装',
            'シリコン塗装3回塗り',
            150,
            'm²',
            3500,
            2100,
          ),
          createItem(
            'item-008-3',
            3,
            '外壁工事',
            '外壁材',
            'シーリング打替',
            '目地部分',
            80,
            'm',
            1200,
            720,
          ),
        ],
      },
      {
        id: 'sec-008-3',
        name: '屋根工事',
        majorCategory: '屋根工事',
        items: [
          createItem(
            'item-008-4',
            4,
            '屋根工事',
            '屋根材',
            '屋根塗装',
            '遮熱塗料3回塗り',
            80,
            'm²',
            4000,
            2400,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 9. 内装リフォーム ====================
  {
    id: 'demo-template-009',
    name: '内装リフォーム',
    description: 'LDK20畳の内装全面リフォーム',
    category: 'リフォーム',
    scope: 'company',
    sections: [
      {
        id: 'sec-009-1',
        name: '内装工事',
        majorCategory: '内装工事',
        items: [
          createItem(
            'item-009-1',
            1,
            '内装工事',
            '床工事',
            'フローリング',
            '複合フローリング',
            35,
            'm²',
            7500,
            4500,
          ),
          createItem(
            'item-009-2',
            2,
            '内装工事',
            '壁・天井工事',
            'クロス',
            'ビニールクロス',
            80,
            'm²',
            1200,
            720,
          ),
          createItem(
            'item-009-3',
            3,
            '内装工事',
            '建具',
            '室内ドア',
            '片開きドア',
            3,
            '箇所',
            45000,
            27000,
          ),
        ],
      },
      {
        id: 'sec-009-2',
        name: '電気工事',
        majorCategory: '電気工事',
        items: [
          createItem(
            'item-009-4',
            4,
            '電気工事',
            '照明器具',
            'LEDシーリングライト',
            '調光・調色機能付',
            2,
            '台',
            25000,
            15000,
          ),
          createItem(
            'item-009-5',
            5,
            '電気工事',
            '照明器具',
            'LEDダウンライト',
            '埋込型',
            6,
            '箇所',
            8000,
            4800,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },

  // ==================== 10. 耐震補強工事 ====================
  {
    id: 'demo-template-010',
    name: '耐震補強工事',
    description: '木造住宅の耐震補強工事',
    category: 'リフォーム',
    scope: 'company',
    sections: [
      {
        id: 'sec-010-1',
        name: '木工事',
        majorCategory: '木工事',
        items: [
          createItem(
            'item-010-1',
            1,
            '木工事',
            '構造材',
            '耐震補強金物',
            'ホールダウン金物',
            12,
            '箇所',
            15000,
            9000,
          ),
          createItem(
            'item-010-2',
            2,
            '木工事',
            '構造材',
            '筋交い追加',
            '木材45×90',
            20,
            '本',
            8000,
            4800,
          ),
          createItem(
            'item-010-3',
            3,
            '木工事',
            '構造材',
            '構造用合板',
            '12mm厚 耐力壁',
            40,
            '枚',
            2500,
            1500,
          ),
        ],
      },
      {
        id: 'sec-010-2',
        name: '基礎工事',
        majorCategory: '基礎工事',
        items: [
          createItem(
            'item-010-4',
            4,
            '基礎工事',
            '基礎本体',
            '基礎補強',
            'アラミド繊維シート貼',
            30,
            'm²',
            12000,
            7200,
          ),
        ],
      },
      {
        id: 'sec-010-3',
        name: '内装工事',
        majorCategory: '内装工事',
        items: [
          createItem(
            'item-010-5',
            5,
            '内装工事',
            '壁・天井工事',
            '内装復旧',
            '補強箇所の復旧',
            1,
            '式',
            150000,
            90000,
          ),
        ],
      },
    ],
    createdBy: 'system',
    createdByName: 'システム',
    createdAt: new Date().toISOString(),
  },
];

/**
 * デモテンプレートを初期化する関数
 * localStorageにデモテンプレートを保存
 */
export function initializeDemoTemplates(): void {
  if (typeof window === 'undefined') return;

  const STORAGE_KEY = 'estimate-v5-templates';
  const existing = localStorage.getItem(STORAGE_KEY);

  // 既存のテンプレートがある場合はデモテンプレートを追加
  if (existing) {
    try {
      const existingTemplates = JSON.parse(existing);
      // デモテンプレートIDがまだない場合のみ追加
      const demoIds = DEMO_TEMPLATES.map((t) => t.id);
      const hasDemo = existingTemplates.some((t: any) =>
        demoIds.includes(t.id),
      );

      if (!hasDemo) {
        const merged = [...existingTemplates, ...DEMO_TEMPLATES];
        localStorage.setItem(STORAGE_KEY, JSON.stringify(merged));
      }
    } catch (error) {
      console.error('既存テンプレートの読み込みに失敗:', error);
      localStorage.setItem(STORAGE_KEY, JSON.stringify(DEMO_TEMPLATES));
    }
  } else {
    // 新規の場合はデモテンプレートをそのまま保存
    localStorage.setItem(STORAGE_KEY, JSON.stringify(DEMO_TEMPLATES));
  }
}
